[package]
name = "snare"
description = "GitHub webhooks runner daemon"
version = "0.4.0"
homepage = "https://tratt.net/laurie/src/snare/"
repository = "https://github.com/softdevteam/snare/"
authors = ["Laurence Tratt <laurie@tratt.net>"]
readme = "README.md"
license = "Apache-2.0 OR MIT"
categories = ["development-tools"]
keywords = ["github", "webhook"]
edition = "2018"

[build-dependencies]
cfgrammar = "0.8"
lrlex = "0.8"
lrpar = "0.8"
rerun_except = "0.1"

[dependencies]
cfgrammar = "0.8"
crypto-mac = "0.7"
getopts = "0.2"
hex = "0.4"
hmac = "0.7"
hyper = "0.13"
json = "0.12"
libc = "0.2"
lrlex = "0.8"
lrpar = "0.8"
nix = "0.17"
num_cpus = "1.12"
percent-encoding = "2.1"
regex = "1.3"
secstr = "0.4"
sha-1 = "0.8"
signal-hook = "0.1"
tempfile = "3.1"
tokio = { version = "0.2", features = ["full"] }
users = "0.10"

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true
